#!/bin/bash

if [ $# -ne 5 ]; then
	echo "Usage: "
	echo "  ./run instance_name username host_ip local_port_to_bind remote_port_to_bind"
	echo "  example: ./run mongodb jsmith 192.168.0.10 27017 27017"
	exit
else
	cmd="docker container run --detach --publish $4:$5 --env local_port=$4 --env remote_port=$5 --env username=$2 --env host_ip=$3 --name $1 tunneler"
	$cmd
	status=$?
	if [ $status -eq 0 ]; then
		echo ""
		echo "Docker $1 instance started"
		echo ""
		echo "To view running instances:"
		echo "  docker ps"
		echo ""
		echo "To stop instance:"
		echo "  docker container stop $1"
		echo ""
		echo "To start instance:"
		echo "  docker container start $1"
		echo ""
		echo "To delete instance:"
		echo "  docker rm $1 --force"
	fi
fi

