#!/bin/bash

if [ ! -f "certs/tunneler_rsa" ]; then
    sudo apt-get install docker.io
    sudo usermod -aG docker $USER
    ssh-keygen -q -t rsa -N '' -f certs/tunneler_rsa     
fi

./build

echo ""
echo "Share this key with your admin:"
echo ""
cat "certs/tunneler_rsa.pub"
echo ""