#!/bin/bash


# autossh -M 0 -4 -T -N -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -L $LOCAL_PORT:localhost:$REMOTE_PORT $HOST_USER@$HOST_IP
autossh -M 0 -4 -T -N -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -L 80:localhost:80 $HOST_USER@$HOST_IP
# apk add curl
# curl localhost:80